# Generated by Django 4.2.16 on 2024-11-26 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dentistoperation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dentistoperation',
            name='dentist',
        ),
        migrations.RemoveField(
            model_name='dentistoperation',
            name='operation',
        ),
        migrations.AlterUniqueTogether(
            name='dentistschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dentistschedule',
            name='dentist',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='operation',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Dentist',
        ),
        migrations.DeleteModel(
            name='DentistOperation',
        ),
        migrations.DeleteModel(
            name='DentistSchedule',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
