# Generated by Django 5.1.3 on 2024-12-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
